cloud:
  aws:
    region:
      static: ap-south-1
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIAXJ3V2P7NZSTYCNWD
      secret-key: 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
    end-point:
      uri: https://sqs.ap-south-1.amazonaws.com/502221406171/SQSPublishConsumeQueue


server:
  port: 8091
